//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPD.DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fault
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fault()
        {
            this.FaultLibraries = new HashSet<FaultLibrary>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public string Location { get; set; }
        public string MachineDescription { get; set; }
        public string FaultDescription { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> Complexity { get; set; }
        public Nullable<int> FaultStatus { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> AssignedTo { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaultLibrary> FaultLibraries { get; set; }
    }
}
