//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPD.DAL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaultLibrary
    {
        public int Id { get; set; }
        public Nullable<int> FaultId { get; set; }
        public string Url { get; set; }
        public string FileName { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual Fault Fault { get; set; }
    }
}
