//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NPD.DAL.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NPDEntities : DbContext
    {
        public NPDEntities()
            : base("name=NPDEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<FaultComplexity> FaultComplexities { get; set; }
        public virtual DbSet<FaultPriority> FaultPriorities { get; set; }
        public virtual DbSet<Fault> Faults { get; set; }
        public virtual DbSet<UsersInfo> UsersInfoes { get; set; }
    }
}
